### ISSUE TITLE
Warning on AMD 7800xt vulkan initialization.

### ISSUE THREAD

**Issue by JulioJerez** [GPUOpen-Drivers/AMD-Gfx-Drivers#11]
HI, I am writing a vulkan compute lib to accelerate some code.
The code seems to work on several gpus, Intel embedded and arch 770 and NVidia starting for 1060.
I recently acquired an amd 7800 with the hope of getting better performance and also to be able to load much large model into gpu memory.
The result has been far, less than I expected, in some case the result fall behind and NVidia 1660 super, so I start checking the code for errors.
so far, the only thing I see in the log is this warning.

vulkan accelerator: AMD Radeon RX 7800 XT

> Debug Report: Validation: Validation
> Warning: [ WARNING-vkGetDeviceProcAddr-device ] | MessageID = 0x22b1fbac | vkGetDeviceProcAddr():
> pName is trying to grab vkGetPhysicalDeviceCalibrateableTimeDomainsKHR which is an instance level function

the warning comes after executing this call bellow is executed

```
void ndBrainGpuContext::CreateLogicalDevice()
{
	m_queue = VK_NULL_HANDLE;
	m_device = VK_NULL_HANDLE;

	const float queue_priority[] = { 1.0f };
	VkDeviceQueueCreateInfo queue_info[1] = {};
	queue_info[0].sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
	queue_info[0].queueFamilyIndex = m_queueFamilyIndex;
	queue_info[0].queueCount = 1;
	queue_info[0].pQueuePriorities = queue_priority;

	VkPhysicalDeviceFeatures deviceFeatures = {};
	VkDeviceCreateInfo create_info = {};
	create_info.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
	create_info.queueCreateInfoCount = sizeof(queue_info) / sizeof(queue_info[0]);
	create_info.pQueueCreateInfos = queue_info;
	create_info.pEnabledFeatures = &deviceFeatures;

	create_info.enabledLayerCount = 1;
	create_info.ppEnabledLayerNames = &m_apiLayers[0];
	//create_info.enabledExtensionCount = 1;
	//create_info.ppEnabledExtensionNames = &m_apiExtensionLayers[0];

	CheckResultVulkan(vkCreateDevice(m_physicalDevice, &create_info, m_allocator, &m_device));
	vkGetDeviceQueue(m_device, m_queueFamilyIndex, 0, &m_queue);
}
```

not sure if this is part of the problem, but is a difference, nonetheless.
so, the question is what do I do to fix that?
most the vulkan initialization boilerplate code taken almost verbatim from tutorials enforced from Chronos org.

edit:
I read the guide line for posting an issue, 
but I do not see how to assig a tag to my post.

**Comment by owenzhangzhengzhong** [comment]
Hi @JulioJerez,

This seems related to this issue:
https://github.com/GPUOpen-Drivers/AMD-Gfx-Drivers/issues/6
Can you try with latest vulkan loader version 1.3.286 and see if it still occurs?

Thanks,
Owen

**Comment by JulioJerez** [comment]
I do not know what you mean by Loader,  if you are referring to Vulkan sdk, 
the version I have was download form here. and it is 
SDK - SDK InstallerVulkanSDK-1.3.283.0

I do not see any download with the number .286 unless you are talking something else.
also a google search come up with site talking about it but not download links.

**Comment by owenzhangzhengzhong** [comment]
This is vulkan loader, you can get the source and documentation here:
https://github.com/KhronosGroup/Vulkan-Loader
You can get the latest version and build it yourself, then put the vulkan-1.dll in the same directory as your game application.
From command line you can see which version of loader you are using by setting environment variable:
set VK_LOADER_DEBUG=info

This is updated via driver update packages.

**Comment by JulioJerez** [comment]
Well, I can't really do that since this is not my choice.
Since this is a glaring issue that seems to affect only some important AMD
gpus,
I am assuming an official fix should be on the way.
Meantime I will just swap the GPU and try again sometime in the future..

Thanks for the answer
and you can close this issue.
Julio

**Comment by JulioJerez** [comment]
further more, when I look at the type of allocations, the list come wit this 

> memoryTypes	0x00000037459be604 
> [0x00000000]	{propertyFlags=0x00000000 heapIndex=0x00000001 }	VkMemoryType
> [0x00000001]	{propertyFlags=0x00000001 heapIndex=0x00000000 }	VkMemoryType
> [0x00000002]	{propertyFlags=0x00000001 heapIndex=0x00000000 }	VkMemoryType
> [0x00000003]	{propertyFlags=0x00000006 heapIndex=0x00000001 }	VkMemoryType
> [0x00000004]	{propertyFlags=0x0000000e heapIndex=0x00000001 }	VkMemoryType
> propertyFlags	0x0000000e	unsigned int
> heapIndex	0x00000001	unsigned int
> [0x00000005]	{propertyFlags=0x00000007 heapIndex=0x00000002 }	VkMemoryType
> [0x00000006]	{propertyFlags=0x00000000 heapIndex=0x00000000 }	VkMemoryType
> 

I am passing options 
VkMemoryPropertyFlags memoryProperty = 
VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT | VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT;

which select entry 5 and that point to which in tern point to the smaller heap. 
I got those option from the tutorials,  
so what is the importance of VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT bit when it seem to be the most memory type?
and why it is use in the hellow world demos?

**Comment by Benualdo** [comment]
Hi, 
I have a 7950XT and I'm having the exact same issue with SDK 1.3.290.0.

Even without any device extension enabled 

```VkDeviceCreateInfo deviceCreateInfo; 
deviceCreateInfo.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
deviceCreateInfo.pNext = nullptr;
deviceCreateInfo.flags = 0;
deviceCreateInfo.queueCreateInfoCount = 1;
deviceCreateInfo.pQueueCreateInfos = queues;
deviceCreateInfo.enabledLayerCount = 0;
deviceCreateInfo.ppEnabledLayerNames = nullptr;
deviceCreateInfo.enabledExtensionCount = 0;// m_deviceExtensionList.getEnabledExtensionCount();
deviceCreateInfo.ppEnabledExtensionNames = 0;// m_deviceExtensionList.getEnabledExtensionNames();
deviceCreateInfo.pEnabledFeatures = nullptr;// &enabledFeatures;
deviceCreateInfo.pNext = nullptr; //&vulkan12Features;

vkCreateDevice(m_vkPhysicalDevice, &deviceCreateInfo, nullptr, &m_vkDevice);
```

I have the following error:

```[Warning] [Device] WARNING : VALIDATION - Message Id Number: 582089644 | Message Id Name: WARNING-vkGetDeviceProcAddr-device
Validation Warning: [ WARNING-vkGetDeviceProcAddr-device ] | MessageID = 0x22b1fbac | vkGetDeviceProcAddr(): pName is trying to grab vkGetPhysicalDeviceCalibrateableTimeDomainsKHR which is an instance level function
```

Thanks.

**Comment by Zhaeong** [comment]
Hi @Benualdo,
There will be an updated vulkan loader in the newest amd driver which should include a fix for this issue.
Else, if you can try this: https://github.com/KhronosGroup/Vulkan-Loader

```
see: https://github.com/KhronosGroup/Vulkan-Loader/blob/main/BUILD.md#building-on-windows
cd Vulkan-Loader
mkdir build
cd build
cmake -A x64 -D UPDATE_DEPS=ON ..
cmake --build .
```

Then put the vulkan-1.dll in the same directory as your application to see if it resolves your issue.

Thanks,
Owen
