### ISSUE TITLE
6700xt fails to initialize with Opengl

### ISSUE THREAD

**Issue by Ralroost** [GPUOpen-Drivers/AMD-Gfx-Drivers#12]
Hello, hope this is the correct place. If not, please correct me.

I've built a PC on the B650M platform, the 6700xt simply won't run opengl applications, though I've established it runs smoothly with Vulkan.
Specs:
MSI B650M Gaming plus wifi with BIOS 1.40
RX6700XT with 24.5.1 versions of drivers (rollback was also tried).
Ryzen 5 7600X
32gb Vengeance at 6000mt/s
EVGA Nova 750 psu

Replaced both the PSU and Mainboard, assuming it had to be one or the other. Also tried a friend's 6600 with drivers completely removed and reinstalled. Also tried disabling the onboard, which kick ins with opengl, to no avail. An error message pops up declaring I need Opengl above 2.1. I can see in the AMD software that 4.6 is installed. Once I disable the onboard, this changes to n/a.
Worth mentioning I've also reinstalled windows multiple times and removed/reinstalled drivers.
Edit: forgot to mention what happens: If I try starting an Opengl game, it will freeze instantly on startup. I can see the first frame of the splash screen and the in game cursor, nothing else. Force closing it on the task manager closes it on-screen, but steam sees the game as still running, choosing "stop running" causes it to get stuck on this process, and no other graphics related process can even be started.

**Comment by Slaw6820** [comment]
Your _Ryzen 5 7600X_ CPU comes with integrated _AMD Radeon Graphics_ GPU. I guess, you have not installed drivers for it, hence the outcome.
You have to download it from here https://www.amd.com/en/support/downloads/drivers.html/processors/ryzen/ryzen-7000-series/amd-ryzen-5-7600x.html
Drivers for _RX 6700XT_ have to be from here https://www.amd.com/en/support/downloads/drivers.html/graphics/radeon-rx/radeon-rx-6000-series/amd-radeon-rx-6700-xt.html

Please install it in that order.

**Comment by Ralroost** [comment]
Thanks for your reply,

I may have explained poorly, the integrated is the one that works. The 6700 card does not. 

Also, both links download the same download file for adrenaline, did I miss something?

I reinstalled the drivers, the card still does nothing when running Opengl on furmark.

**Comment by Slaw6820** [comment]
How about change the graphics settings in Windows? It should look like this:

![image](https://github.com/GPUOpen-Drivers/AMD-Gfx-Drivers/assets/126240944/f088b255-7f4c-4970-aa84-eaa4521bec78)

**Comment by Ralroost** [comment]
Unfortunately that also had no effect

**Comment by Ralroost** [comment]
I've solved the issue: I had the HDMI cable plugged into the Mainboard rather than the GPU. In my defence, I've used laptops the last ten years that only had one slot. Embarrassing.

Thanks a lot for your help.
