### ISSUE TITLE
VK_KHR_push_descriptor

### ISSUE THREAD

**Issue by STS-dev34** [GPUOpen-Drivers/AMD-Gfx-Drivers#13]
We are a software development company creating CAD and Mapping software. We would like to recommend a list of graphics cards for our clients. To this end we would like to know if the Vulkan extension "VK_KHR_push_descriptor" is or will be fully supported by AMD graphics. We have currently tested this extension on the following AMD Cards or Embedded Graphics and are unable to get this extension to work even though we have installed the "latest" drivers:
AMD Radeon RX 6600 XT
AMD Ryzen 7 5700G with Radeon Graphics
AMD Ryzen 5 5600G with Radeon Graphics

This extension has been tested to work for our software on numerous other (non-AMD) graphics systems. It would be highly appreciated if this could be considered to be high priority.
Kind Regards

**Comment by owenzhangzhengzhong** [comment]
Hi @STS-dev34,

VK_KHR_push_descriptor has been supported for a while, can you provide more information on your issue? Also environment information, and vulkaninfo output would be helpful to see if we can help with this problem.

Thanks,
Owen

**Comment by STS-dev34** [comment]
Hi Owen

Thank you for your reply.

We wanted to first make sure that the extension is fully supported by AMD as we did find information that it is.  We are therefore still investigating if we are doing something “wrong” which AMD graphics are intolerant of.  We should be able to confirm this by early next week.

If we still have the problem, it is probably best if we create the smallest possible application which manifests the problem and forward that code to you. Do you also see this as the way forward?

Regards

Spencer

**Comment by STS-dev34** [comment]
Hi Owen

Thank you for your reply and willingness to help resolve this issue. We have attached the relevant files for your attention. The keyword "SmartTechAdded" can be searched for through main.cpp to find our changes

Unfortunately, we have had issues with push descriptors on several AMD machines, but not on NVIDIA machines. As previously mentioned, we have not been sure if we are doing something wrong (and thereby causing undefined behaviour), or if there is another issue present.

Initially, we struggled with an issue related to the validation layers themselves. After using GPU-assisted validation, we realized a mistake in our own code - we were not correctly binding the full "range" for the bound descriptor set layout. However, the Khronos GPU-based validation layers themselves were crashing in an attempt to report this issue to us, which made this problem difficult to debug.

The above issue has now been fixed, however we are still facing issues in our CAD application. Specifically, the Vulkan device gets lost during command buffer submission. Fortunately, we have been able to create an isolated example which demonstrates this issue, and have attached this in a Visual Studio project. The example is based on the well-known "Vulkan Tutorial" (specifically Chapter 23), except for our changes.

In our CAD application, we wish to selectively use push descriptors for certain descriptor slots. We have demonstrated this in the attached example. Essentially, instead of using the "standard" uniform buffer for camera information (as the tutorial does), we now also make use of a secondary "push" uniform buffer only for the model matrix, which we transform using a simple scale for visual feedback. On NVIDIA machines, the original triangle appears successfully scaled, however the program hangs on some AMD machines. Where there is an additional graphics card present on the AMD machine, it works successfully.

The keyword "SmartTechAdded" can be searched for through main.cpp to find our changes. The project should be self-contained (including the GLFW and glm libraries) except for potentially the Vulkan SDK path. We have also included the shaders with a compile script. The problem persists both in release and debug when run from Visual Studio and directly from the .exe. Please note however that the "shaders" folder needs to be present alongside the .exe when running it directly, as opposed to alongside the project when running from Visual Studio.

Below is the AMD hardware we are using on some of our machines and the resultant status. All machines have the Gigabyte Aorus Elite motherboards (B550 and X570) recommended for AMD processors  

Processor	Graphics	Status
Ryzen 5 5600G	Embedded	                Not working
Ryzen 7 5700G	Embedded	                Not working
Ryzen 9 5900X	        RX 6600 XT Strix Oc 8G	Working

Your attention to this matter and timeous response would be greatly appreciated, as we are waiting to release the latest version of our software as soon as possible.

Kind regards

Gary Allen
Developer

**Comment by STS-dev34** [comment]
Hi Owen

The sample code from Gary is ± 19MB zipped. Please confirm it was received.

Thanks

Hilary

**Comment by owenzhangzhengzhong** [comment]
Fixed in upcoming driver release.
