### ISSUE TITLE
Segmentation fault of AMD GPU on a simple fragment shader

### ISSUE THREAD

**Issue by mitdemverkaufer** [GPUOpen-Drivers/AMD-Gfx-Drivers#16]
The AMD GPU throws a segmentation fault during the execution of shader program. Such segmentation fault does not occur on Intel GPUs.

## Description of the issue

The following shader is a minimal example that reproduces the issue:

```glsl
#version 310 es

precision highp float;
precision highp int;

const uint UINT_MAX = 4294967295u;

layout(location = 0) out vec4 fragColor;

void main() {
  uint t1 = uint(gl_FragCoord.x);
  uint t2 = uint(gl_FragCoord.y);
  uint x1 = t1 | t1;    // x1 = t1
  uint c1 = t1 > 0u && t2 > 0u && t1 > UINT_MAX / t2 ? 0u : 1u; // c1 = 1 for all pixels
  uint c2 = t1 > 0u && x1 > 0u && t1 > UINT_MAX / x1 ? 0u : 1u; // c2 = 1 for all pixels
  uint var0 = c1 + c2;  // var0 = 2
  fragColor = vec4(var0);   // output white color
}
```

The variables `t1` and `t2` are the rounded coordiates of the rendered pixel. The variable `x1` is the bitwise OR of `t1` and `t1`, which should be equal to `t1`. At line `uint c1 = ...`, the ternary condition `t1 > 0u && x2 > 0u && t1 > UINT_MAX / x2` holds for all pixels, since we set the screen size to be (256, 256) and thus `t2 > 0u && t1 > UINT_MAX / t2` is always false. Therefore, `c1` is always 1. Similarly, `c2` is also always 1, and thus `var0` is always 2. The expected output color of the shader is white.

However, the AMD GPU throws a segmentation fault during the execution of the shader.

Interestingly, if we change the line `uint x1 = t1 | t1;` to `uint x1 = t1;`, or remove the ternary condition `t1 > 0u` for either `c1` or `c2`, or even define `c2` before `c1`, the segmentation fault does not occur.

Such bug occurs on both OpenGL and Vulkan (if we compile the glsl shader to spirv). The bug happens even if you do not optimize the spirv shader. The bug does not occur on Intel GPUs.

## Environment

- OS: Windows 10
- GPU:
  - AMD Radeon RX 6400
  - Driver version: 32.0.11021.1011
  - Driver date: 6/20/2024

## Steps to reproduce

I provide a minimal package that reproduces the issue. The package contains a minimal Vulkan application to compile and execute the fragment shader. Please refer to the README.md in the package. It should take less than a minute to reproduce.

You can download the package [here](https://www.dropbox.com/scl/fi/9r6fdbbxvg00n9ij95r3z/amd_ter.tar.gz?rlkey=jm3m8bhup14yqx5ay8sc5olfr&st=1d0tq58o&dl=0)

**Comment by owenzhangzhengzhong** [comment]
Hi @mitdemverkaufer,

I was able to reproduce this issue and we'll look into it, thanks for reporting.

Owen

**Comment by owenzhangzhengzhong** [comment]
Hi @mitdemverkaufer,

We've implemented a fix to this issue, and should be part of next release.

Thanks for reporting it,
Owen
