### ISSUE TITLE
VK_EXT_shader_object

### ISSUE THREAD

**Issue by cppearl** [GPUOpen-Drivers/AMD-Gfx-Drivers#17]
Can we expect implementation for VK_EXT_shader_object for Radeon GPUs ?

I saw that a lot of Nvidia GPUs support it, why AMD does not do same for Radeons ? This extension looks very useful for developers (and for speeding up the launching process of the software for users).

**Comment by owenzhangzhengzhong** [comment]
Hi @Cijei03,

Thanks for the question. We are working on support for VK_EXT_shader_object. No timelines for ETAs can be given publicly, but look out for it in the upcoming releases.

Thanks,
Owen

**Comment by tzdimi** [comment]
Latest driver 24.9.1 includes support for VK_EXT_shader_object.

Thx devs and AMD for including it!!!! :)
