### ISSUE TITLE
AMD Radeon RX 6400 GPU throws an exception about a block branching to a loop continue target

### ISSUE THREAD

**Issue by mitdemverkaufer** [GPUOpen-Drivers/AMD-Gfx-Drivers#18]
## Description

The AMD GPU throws an exception when running a fragment shader program:

```txt
Block '34[%34]' branches to the loop continue target '31[%31]', but is not contained in the associated loop construct '20[%20]'
  OpBranch %31
```

The fragment shader is well-formed and does not contain undefined behavior. The shader can be compiled without any warning or errors by the `glslangValidator` tool. However, when it is executed on the AMD GPU, the GPU throws the exception mentioned above.

## System information

<details><summary>click to expand</summary>

- OS: Windows 10 Enterprise 64-bit (22H2, OS build: 19045.4651)
- Visual Studio: 2022 Community
- LunarG Vulkan SDK: 1.3.290.0
- GPU0:
  - Intel(R) UHD Graphics 730
  - Driver version: 31.0.101.5592
  - Driver date: 6/19/2024

- GPU1: (Selected by the Vulkan application)
  - AMD Radeon RX 6400
  - Driver version: 32.0.11021.1011
  - Driver date: 6/20/2024

</details>

## Steps to reproduce

The package for reproducing the issue can be downloaded from [here](https://www.dropbox.com/scl/fi/vofrrmpmaejs9h49iu2gj/amd_br_loop.tar.gz?rlkey=4cdemxmcvtzv1xlk965n3iztr&st=44vhvke0&dl=0). The package contains the following major files:

- `README.md`: The detailed description of the system information and steps to reproduce the issue.
- `src/main.cpp`: The source code of a minimal Vulkan application that compiles and executes the fragment shader program.
- `glsl/shader.frag`: The GLSL source code of the fragment shader program that causes the exception on the AMD GPU.
- `spv/*`: The SPIR-V binary files compiled from the GLSL shader programs.

To reproduce the issue, simply follow the steps in `README.md`. It should take only a few minutes to reproduce the issue.

**Comment by owenzhangzhengzhong** [comment]
Hi @mitdemverkaufer,

The full error message is (also included in your readme):
validation layer: Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-08737 ] | MessageID = 0xa5625282 | vkCreateShaderModule(): pCreateInfo->pCode (spirv-val produced an error):
Block '34[%34]' branches to the loop continue target '31[%31]', but is not contained in the associated loop construct '20[%20]'
  OpBranch %31
. The Vulkan spec states: If pCode is a pointer to SPIR-V code, pCode must adhere to the validation rules described by the Validation Rules within a Module section of the SPIR-V Environment appendix (https://vulkan.lunarg.com/doc/view/1.3.290.0/windows/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-08737)

This is caught by the vulkan validation layer, which is at a layer above AMD's vulkan driver (note, running this on nvidia hardware will produce the same validation error).

You can use tools include in Vulkan SDK to check:
-spirv-dis to disassemble spv file, see attached:
[spirvDisFrag.txt](https://github.com/user-attachments/files/16641930/spirvDisFrag.txt)

-spirv-val to validate spv file, which shows:
error: line 56: Block '34[%34]' branches to the loop continue target '31[%31]', but is not contained in the associated loop construct '20[%20]'
  OpBranch %31

This seems to be problematic line:
         %34 = OpLabel
               OpBranch %31

You can change the glsl shader and play around with its disassembly, and verify its issue here:
https://vulkan.lunarg.com/doc/view/1.3.290.0/windows/1.3-extensions/vkspec.html#spirvenv-module-validation

This could be an issue with spirv tools, which you can create ticket there:
https://github.com/KhronosGroup/SPIRV-Tools/issues

Thanks,
Owen
