### ISSUE TITLE
Updated RTX Remix issues

### ISSUE THREAD

**Issue by KingVulpes** [GPUOpen-Drivers/AMD-Gfx-Drivers#19]
There are a few issues still on RTX Remix for both RDNA 2 and RDNA 3

RDNA 2: RDNA 2 performance is still suffering horribly, and I know it's not the GPU's themselves because over on Linux they perform much better to the point they can even match some RDNA 3 cards in performance. Even the Remix devs think RDNA 2 should be performing better but something driver related is holding it back, This is the only issue with RDNA 2 on Windows and RTX Remix

(Note: Even the RX 5700xt on Linux using Mesa does better than some RDNA 2 cards showing how bad the performance is)

RDNA 3: RDNA 3 has more problems. the first and most noticeable is Volumetric Lighting being glitched, this does not occur on Linux leading me to believe that the issue is indeed driver related. There was a D3D error in earlier Remix versions but the Remix devs fixed this issue in newer runtimes, therefore the issue only occurs if going back to older runtimes before 0.5.1 . Another issue is there is still a performance gap between Linux and Windows, even though RDNA 3 does perform better than RDNA 2 on Window, I suspect because driver support for Remix was never added to Windows, the cards are still being underutilized

AFMF 2: This does not work with RTX Remix despite being a Vulkan program, I suspect this is because it uses DXVK and the driver has problems detecting that, especially since Remix does rendering differently 

I do think these issues should be easier to fix than most since RTX Remix is open source and should provide details into how it works, on top of that the devs will integrate any contributions made to the github into the main releases.

**Comment by KingVulpes** [comment]
RTX Remix github: https://github.com/NVIDIAGameWorks/rtx-remix

**Comment by owenzhangzhengzhong** [comment]
Hi @KingVulpes ,

Thanks for reporting this issue, this looks to be a framework to remaster classic DirectX 8 and 9 games. And the link you provided are the tools that provide the translation layer between x86 to x64, and then dx calls to vulkan. As we are unfamiliar with this framework, to speed things up, can you provide a compilable and executable sample which highlights this issue?

Thanks,
Owen

**Comment by KingVulpes** [comment]
The best example would be Portal with RTX: https://store.steampowered.com/app/2012840/Portal_with_RTX/
it was completely remastered using the technology and was updated with the RDNA 3 D3D fix so those cards can load into it. Logs are also generated by default in the files so that could give some more depth on how it loads things.

**Comment by KingVulpes** [comment]
> Hi @KingVulpes ,
> 
> Thanks for reporting this issue, this looks to be a framework to remaster classic DirectX 8 and 9 games. And the link you provided are the tools that provide the translation layer between x86 to x64, and then dx calls to vulkan. As we are unfamiliar with this framework, to speed things up, can you provide a compilable and executable sample which highlights this issue?
> 
> Thanks, Owen

The best example would be Portal with RTX: https://store.steampowered.com/app/2012840/Portal_with_RTX/
it was completely remastered using the technology and was updated with the RDNA 3 D3D fix so those cards can load into it. Logs are also generated by default in the files so that could give some more depth on how it loads things.

**Comment by McMasterGold** [comment]
As a user of an RX 6700 10GB, playing the current Steam version of Portal RTX on Linux with the Mesa/RADV drivers boosts performance by 4-5x compared to Windows, which brings the game from a completely unplayable state to a much more usable one. Profiling the game on RDNA 2 and Windows shows the vector registers blown out by a single shader, which results in the GPU being underutilised and the RT cores not contributing much to the path-traced rendering.

One thing that helped towards greatly improved performance on Linux is defaulting to RT pipelines for the RADV driver: https://github.com/NVIDIAGameWorks/dxvk-remix/commit/1820ca192ddd32fdc8165cc868768e74ffd064c8 Perhaps a similar fix could be investigated for the Windows drivers?

**Comment by KingVulpes** [comment]
The Remix devs are also available to talk to for help through their official discord server (if thats an option): https://discord.gg/rtxremix
They could probably provide much more insight

**Comment by owenzhangzhengzhong** [comment]
Hi @KingVulpes , @McMasterGold ,

Thanks for the info, we will be investigating this issue.

Owen

**Comment by owenzhangzhengzhong** [comment]
Hey @KingVulpes,

We did some preliminary investigation into RTX Remix source there seems to be some issues whereby the app would 
a) consistently select the first driver returned by vulkan instead of the best one
b) seems to hardcode certain parameters (such as number of queues) instead of inspecting capabilities properly
As this is a competitors product, we'll be refraining from further investigation into this.

Thanks for your question,
Owen

**Comment by KingVulpes** [comment]
> Hey @KingVulpes,
> 
> We did some preliminary investigation into RTX Remix source there seems to be some issues whereby the app would 
> a) consistently select the first driver returned by vulkan instead of the best one
> b) seems to hardcode certain parameters (such as number of queues) instead of inspecting capabilities properly
> As this is a competitors product, we'll be refraining from further investigation into this.
> 
> Thanks for your question,
> Owen

Thanks for the insight, I'll definitely send this over to the RTX Remix team
Really appreciate it ❤️

**Comment by KingVulpes** [comment]
> Hey [@KingVulpes](https://github.com/KingVulpes),
> 
> We did some preliminary investigation into RTX Remix source there seems to be some issues whereby the app would a) consistently select the first driver returned by vulkan instead of the best one b) seems to hardcode certain parameters (such as number of queues) instead of inspecting capabilities properly As this is a competitors product, we'll be refraining from further investigation into this.
> 
> Thanks for your question, Owen

So the Remix devs tried fixing this and the RDNA 2 issues are still apparent on Windows, for RADV this still isn't an issue which still shows that there is something going on with the AMDVLK side. As we work on our Portal 2 with RTX remaster, it's more important to use than before that these issues are addressed, Remix is now out of beta and you can find an example of their 1.0.0 runtime at: https://store.steampowered.com/app/2477290/HalfLife_2_RTX/
If needed
