### ISSUE TITLE
VK_DYNAMIC_STATE_RASTERIZATION_SAMPLES_EXT does not work.

### ISSUE THREAD

**Issue by tzdimi** [GPUOpen-Drivers/AMD-Gfx-Drivers#21]
This is a follow up from Developer Forums  https://community.amd.com/t5/opengl-vulkan/possible-bug-in-vk-extended-dynamic-state3-and-multisampling/td-p/659006 (read it for more info, leaving it here also, so it maybe fixed)

VK_DYNAMIC_STATE_RASTERIZATION_SAMPLES_EXT and the relevant vkCmdSetRasterizationSamplesEXT seems to be broken.  Even if the dynamic state is enabled and vkCmdSetRasterizationSamplesEXT is called before rendering, there is no effect in the final rendering as if there is no multisampling happening at all. Everything works normal if multisampling is enabled with the old non dynamic way.

**Comment by owenzhangzhengzhong** [comment]
Hi @tzdimi,

Thanks for the issue, looks like the original links are no longer working. Have you tried with the latest drivers? Also, to speed things up, can you also upload sample source code that's compilable showing this issue?

Thanks,
Owen

**Comment by tzdimi** [comment]
Hi @owenzhangzhengzhong 

I dont know if the issue appeared at driver 23.12.1 but then was first encountered. With latest driver 24.8.1 is still not working correctly. I dont have a minimum compilable example to show case it since its part of a bigger project.

Windows 11
6900xt 
5900x
Visual Studio 2022.
driver 24.8.1

 here a rough example.

Old way (non dynamic multisample):

VkPipelineMultisampleStateCreateInfo multisampling{};
multisampling.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
multisampling.sampleShadingEnable = VK_TRUE
multisampling.rasterizationSamples = VK_SAMPLE_COUNT_4_BIT
multisampling.minSampleShading = 0.25f; 
multisampling.pSampleMask = nullptr; 
multisampling.alphaToCoverageEnable = VK_FALSE; 
multisampling.alphaToOneEnable = VK_FALSE; 

and then normal rendering bind various resource and issue draw cmds.

Dynamic way:

during device creation enable the dynamic features.

VkPhysicalDeviceExtendedDynamicState3FeaturesEXT extended_dynamic_state3_features{};
extended_dynamic_state3_features.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTENDED_DYNAMIC_STATE_3_FEATURES_EXT;
extended_dynamic_state3_features.extendedDynamicState3RasterizationSamples = true;
extended_dynamic_state3_features.extendedDynamicState3PolygonMode = true;
extended_dynamic_state3_features.extendedDynamicState3AlphaToCoverageEnable = true;
extended_dynamic_state3_features.extendedDynamicState3SampleMask = true;
extended_dynamic_state3_features.extendedDynamicState3ColorBlendEnable = true
extended_dynamic_state3_features.extendedDynamicState3ColorBlendEquation = true;
extended_dynamic_state3_features.extendedDynamicState3LogicOpEnable = true;
extended_dynamic_state3_features.extendedDynamicState3ColorWriteMask = true;

during pipeline creation create pipeline with dynamic state for multisample rasterization samples.

VkPipelineDynamicStateCreateInfo dynamic_state_info{};
dynamic_state_info.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
const VkDynamicState dynamicStates[] = { 
VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT, VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT,
VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE, VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE, VK_DYNAMIC_STATE_DEPTH_COMPARE_OP,
VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE,
VK_DYNAMIC_STATE_POLYGON_MODE_EXT , 
VK_DYNAMIC_STATE_RASTERIZATION_SAMPLES_EXT };
dynamic_state_info.dynamicStateCount = static_cast<uint32_t>(std::size(dynamicStates));
dynamic_state_info.pDynamicStates = dynamicStates;

and finaly before rendering:

vkCmdSetRasterizationSamplesEXT(cmd_buffer, VK_SAMPLE_COUNT_4_BIT);

bind resources etc and issue draw cmds.

There are no error messages from debug layers etc.

**Comment by owenzhangzhengzhong** [comment]
Hi @tzdimi,

I've reproduced the issue on our end, and will be working on it.

Thanks,
Owen

**Comment by owenzhangzhengzhong** [comment]
Hi @tzdimi,

Reproduced issue has been fixed and should be included in an upcoming release.

Thanks for report this,
Owen
