### ISSUE TITLE
OpenGL driver transparency bug

### ISSUE THREAD

**Issue by godlikedh** [GPUOpen-Drivers/AMD-Gfx-Drivers#29]
Hi, looking for help, i think there is bug in OpenGL drivers. Was doing some programming with rust egui, i found out that i can't create transparent windows, investigating it further lead that function

```
 BOOL wglGetPixelFormatAttribivARB(HDC hdc,
                                      int iPixelFormat,
                                      int iLayerPlane,
                                      UINT nAttributes,
                                      const int *piAttributes,
                                      int *piValues);
```
always return 0 for attribute

`WGL_TRANSPARENT_ARB`
This reproduces for all possible pixel format ids that  are returned by 

`wglChoosePixelFormatARB`

There are number of "transparency" related bugs on AMD community forms, may be some of ther are related to this issue.

 

My Setup:

OS:  Microsoft Windows 10 Pro 

OS Version: 10.0.19045 Build19045

Driver Version: 24.20.19.01-241011a-409016C-AMD-Software-Adrenalin-Edition

OpenGL® Driver Version: 24.10.240702_2e2ba6f

GPU: AMD Radeon RX 5700 XT

goodplay on AMD Forums suggested to post it here
original thread https://community.amd.com/t5/pc-drivers-software/opengl-driver-transparency-bug/m-p/724891#M199475

**Comment by baozholu-AMD** [comment]
@godlikedh  we only support WGL_TRANSPARENT_ARB on workstation cards now.
