### ISSUE TITLE
VK_LAYER_AMD_switchable_graphics calls vkGetDeviceProcAddr on Instance function

### ISSUE THREAD

**Issue by spencer-lunarg** [GPUOpen-Drivers/AMD-Gfx-Drivers#6]
From https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8048

 The `VK_LAYER_AMD_switchable_graphics` layer is calling `vkGetDeviceProcAddr` on an instance level function (`vkGetPhysicalDeviceCalibrateableTimeDomainsKHR`) which will return null and the validation layers are reporting a warning.

There is a `vkGetInstanceProcAddr` that should be used instead

**Comment by soararing** [comment]
I can reproduce the issue with current public release driver 24.5.1, and this issue is root-caused to be with Vulkan loader, in our public driver package 24.5.1, the Vulkan loader version is 1.3.261, if I replace it with latest Vulkan loader version 1.3.286, this issue is gone.

**Comment by jinjianrong** [comment]
@spencer-lunarg could you confirm that this is an issue in Vulkan loader and fixed in new version?

**Comment by spencer-lunarg** [comment]
@onhi is the original report author (https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8048), I am just helping move the issue around

**Comment by owenzhangzhengzhong** [comment]
Fixed in latest vulkan loader, which will be included in next amd driver update.
