### ISSUE TITLE
GL_MAX_TEXTURE_SIZE hardware limited or increasable?

### ISSUE THREAD

**Issue by DemonGamingLP** [GPUOpen-Drivers/AMD-Gfx-Drivers#7]
Hello there,
previously i only had Nvidia GPUs and recently got an AMD GPU for the first time and noticed its GL_MAX_TEXTURE_SIZE is at 16k x 16k while Nvidias is higher.

while this is no issue basically almost everywhere there is at least one case where this causes issues: Minecraf high Resolution resource packs.

so i wondered:
-is AMD planning to increase the limit anytime soon?
-is this actually a hardware limitation (which i would not really understand since i doubt the gpus are not powerful enough) or
-is this limit changeable via a driver update?

thanks in advance!

**Comment by lubaozho** [comment]
The next generation of AMD GPUs will support the same GL_MAX_TEXTURE_SIZE as Nvidia. Thanks.

**Comment by baozholu-AMD** [comment]
GL_MAX_TEXTURE_SIZE = 16k is a hardware limitation. Thanks.
